language: generic

#super user permissions needed
sudo: true

#install docker service
services:
  - docker

#things to do before main tasks are done
before_install:
  - docker build -t damilare77/docker-react -f Dockerfile .

#contains all the commands that needs to execute the test suite
#for testing
#- docker run -e CI=true damilare77/docker-react npm run test -- --coverage
#script:
#  - docker run damilare77/docker-react

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-161456384528"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
