language: generic

#super user permissions needed
sudo: true

#install docker service
services:
  - docker

#things to do before main tasks are done
before_install:
  - docker build -t damilare77/docker-react -f Dockerfile.dev .

#contains all the commands that needs to execute the test suite
script:
  - docker run -e CI=true damilare77/docker-react yarn run test
