language: generic

#super user permissions needed
sudo: true

#install docker service
services:
  - docker

#things to do before main tasks are done
before_install:
  - docker build -t damilare77/docker-react -f Dockerfile.dev .

#contains all the commands that needs to execute the test suite
script:
  - docker run -e CI=true damilare77/docker-react yarn run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-161456384528"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
